version: 1.1.0

global-settings:
 time-source: internal-realtime
 
sil-kit:
  participant-name: CANoe4SW_SE
  config-file-path: ../CANoe_SILKit_config.silkit.yaml

can-networks:
  - name: CAN1    
    mapping: external-sil-kit

simulation-nodes:
  - name: SilKitDummyNode
    network-assignments:
      - network: CAN1